### ISSUE TITLE
Where is the docker file saved/downloaded

### ISSUE THREAD

**Issue by Jacob-Branch** [Kiel-AI/gpt-neo-deployment#2]
Hello! I was gonna try out the api for a project im working on, but while the docker compose was running my vscode crashed, and now i dont have enough room on my hard drive for the download, where can i find the downloaded files so i can delete them/is it possible to download the files on my other hard drive, and if so, how?

**Comment by mattinannt** [comment]
Hi @Jacob-Branch
docker-compose builds the image and saves all downloaded models in this image. You need to remove that (maybe dangling) image using docker: https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
You can easily clean all docker images and stopped container using this command:
```
docker system prune -a
```
Maybe then try using the smaller 1.3B model for testing. For that change the model in the `.env` file to:
```
GPT_MODEL=EleutherAI/gpt-neo-1.3B
```
