### ISSUE TITLE
non-zero code: 137 / The process died after completing downloading the model file though memory and HD space is available!

### ISSUE THREAD

**Issue by zenny** [Kiel-AI/gpt-neo-deployment#3]
Hi,

The process died after downloading huge 10GB file (where is the copy located so that one does not have to download again?):

```
Downloading: 100%|█████
       │ █████| 10.7G/10.7G [1:49:26<00:00, 1.63MB/s]Killed
 309   │ The command '/bin/sh -c python3 download_model.py' returned a non-zero code: 137
 310   │ ERROR: Service 'gpt-neo-api' failed to build : Build failed'
```

I checked whether it is a HDD issue or memory issue, but does not seem the cause:

```
$ df -h
 322   │ Filesystem                Size      Used Available Use% Mounted on
 323   │ devtmpfs                 10.0M         0     10.0M   0% /dev
 324   │ shm                       3.9G         0      3.9G   0% /dev/shm
 325   │ /dev/vg0/lv_root         93.9G     39.3G     49.8G  44% /
 326   │ tmpfs                     1.6G    632.0K      1.6G   0% /run
 327   │ df: /sys/kernel/debug/tracing: Permission denied
 328   │ /dev/sda1                92.8M     19.6M     66.3M  23% /boot
```

Memory allocated:

```
$ free -mh
 315   │               total        used        free      shared
 316   │ buff/cache   available
 317   │ Mem:          16016         371       14849          42
 318   │        796       15426
 319   │ Swap:          4096           0        4096
```

So where did I go wrong? (I am trying to install on an intranet without any access from the outside network, fyi)

Cheers,

**Comment by mattinannt** [comment]
Hi @zenny 
the model is downloaded during the building process of the docker image and is stored within the image. So the model only downloads once during building and not every time you start a container.

The way the script works is that it depends on the internet to download the GPT-Neo Image. If your server doesn't have internet access it shouldn't have been possible to download the model; but maybe a solution would be to build the image on a machine with internet access and then transfer the image to the machine on the intranet?
Never done that before, but seems it could be done with `docker save` and `docker load`:
https://docs.docker.com/engine/reference/commandline/save/

Additionally you can also use the smaller 1.3B model for testing. For that change the model in the `.env` file to:
```
GPT_MODEL=EleutherAI/gpt-neo-1.3B
```
